check secrets

diff --git a/.github/workflows/web-release.yml b/.github/workflows/web-release.yml
--- a/.github/workflows/web-release.yml
+++ b/.github/workflows/web-release.yml
@@ -11,6 +11,16 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+      - name: Ensure Secrets Are Set
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
+            echo "Error: DOCKERHUB_USERNAME is not set!"
+            exit 1
+          fi
+          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
+            echo "Error: DOCKERHUB_TOKEN is not set!"
+            exit 1
+          fi
       - uses: actions/checkout@v4
       - uses: docker/setup-qemu-action@v3
       - uses: docker/setup-buildx-action@v3
